ServisFy/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;
using ServisFy.Models.Auth;

namespace ServisFy.Controllers
{
    public class AuthController : Controller
    {
        public IActionResult Login()
        {
            return View();

        }

        [HttpPost]
        public IActionResult Login(LoginDto Login)
        {
            return RedirectToAction("Dash", "Dash");
        }
    }
}

ServisFy/Controllers/AyarlarController.cs
using Microsoft.AspNetCore.Mvc;
using ServisFy.Models.Auth;

namespace ServisFy.Controllers
{
    public class AyarlarController : Controller
    {
        public IActionResult Ayarlar()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Ayarlar(AyarlarDto ayarlar)
        {
            // Apiye yollama işlemleri vs.  Session Araştırılacak

            return RedirectToAction("Dash", "Dash");
        }
    }
}

ServisFy/Controllers/BildirimController.cs
using Microsoft.AspNetCore.Mvc;

namespace ServisFy.Controllers
{
    public class BildirimController : Controller
    {
        public IActionResult Bildirimler()
        {
            return View();
        }
    }
}

ServisFy/Controllers/DashController.cs
using Microsoft.AspNetCore.Mvc;

namespace ServisFy.Controllers
{
    public class DashController : Controller
    {
        public IActionResult Dash()
        {
            return View();
        }
    }
}

ServisFy/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace ServisFy.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ServisFy/Controllers/OgrNeredeController.cs
using Microsoft.AspNetCore.Mvc;

namespace ServisFy.Controllers
{
    public class OgrNeredeController : Controller
    {
        public IActionResult OgrNrd()
        {
            return View();
        }
    }
}

ServisFy/Controllers/OkulController.cs
using Microsoft.AspNetCore.Mvc;
using ServisFy.Models.Auth;

namespace ServisFy.Controllers
{
    public class OkulController : Controller
    {
        public IActionResult Okul()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Okul(OkulDto okul)
        {
            // Apiye yollama işlemleri vs.  Session Araştırılacak

            return RedirectToAction("Yonetim", "Yonetim");
        }
    }
}

ServisFy/Controllers/RegisterController.cs
using Microsoft.AspNetCore.Mvc;
using ServisFy.Models.Auth;

namespace ServisFy.Controllers
{
	public class RegisterController : Controller
	{
		public IActionResult Register()
		{
			return View();
		}

        [HttpPost]
		public IActionResult Register(RegisterDto register)
        {
			// Apiye yollama işlemleri vs.  Session Araştırılacak

			return RedirectToAction("Login", "Auth");
        }
	}
}

ServisFy/Controllers/ServisController.cs
using Microsoft.AspNetCore.Mvc;

namespace ServisFy.Controllers
{
    public class ServisController : Controller
    {
        public IActionResult Servis()
        {
            return View();
        }
    }
}

ServisFy/Controllers/YeniservisController.cs
using Microsoft.AspNetCore.Mvc;
using ServisFy.Models.Auth;

namespace ServisFy.Controllers
{
    public class YeniservisController : Controller
    {
        public IActionResult Yeniservis()
        {
            return View();
        }
        [HttpPost]
        public IActionResult YeniServis(YeniServisDto yeniServis)
        {

            return RedirectToAction("Yonetim", "Yonetim");
        }
    }
}

ServisFy/Controllers/YenisurucuController.cs
using Microsoft.AspNetCore.Mvc;
using ServisFy.Models.Auth;

namespace ServisFy.Controllers
{
    public class YenisurucuController : Controller
    {
        public IActionResult Yenisurucu()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Yenisurucu(YeniSurucuDto yeniSurucu)
        {

            return RedirectToAction("Yonetim", "Yonetim");
        }
    }
}

ServisFy/Controllers/YonetimController.cs
using Microsoft.AspNetCore.Mvc;

namespace ServisFy.Controllers
{
    public class YonetimController : Controller
    {
        public IActionResult Yonetim()
        {
            return View();
        }
    }
}

ServisFy/Views/Ayarlar/Ayarlar.cshtml
@{
	ViewData["Title"] = "Ayarlar";
	Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}
@model ServisFy.Models.Auth.AyarlarDto

<head>
		<link href="~/ayarlar/style.css" rel="stylesheet">

</head>
<body>
	<div class="wrapper bg-white mt-sm-5 text-center">
		<h4 class="pb-4 border-bottom">Hesap Ayarları</h4>
		<div class="d-flex align-items-center py-3 border-bottom">
			<img src="~/Dashboard/images/faces/face27.jpg" class="img" alt="" width="300">
			<div class="pl-sm-4 pl-2 text-center" id="img-section">
				<br>

				<b>Profil Resmi</b>

				<br>
				<br>
				<button class="btn button border"><b>Yükle</b></button>
			</div>
		</div>
		<div class="py-6 text-center">
			<div class="row py-6 text-center">
				@using (Html.BeginForm())
				{
					<div class="form-group">
						@Html.TextBoxFor(x=>x.k_adi,new {@class="form-control form-control-lg text-center",@placeholder="Adınız", @required="required"})

					</div>
					<div class="form-group">
						@Html.TextBoxFor(x=>x.k_soyadi,new {@class="form-control form-control-lg text-center",@placeholder="Soyadınız", @required="required"})
					</div>

					<div class="form-group">
						@Html.TextBoxFor(x=>x.k_mail,new {@class="form-control form-control-lg text-center",@placeholder="E-Posta",@type="email", @required="required"})

					</div>
					<div class="form-group">
						@Html.TextBoxFor(x=>x.tel_no,new {@class="form-control form-control-lg text-center",@placeholder="Tel No", @required="required"})

					</div>






					<div class="py-3 pb-4 border-bottom text-center">
						<input type="submit" formmethod="post" formaction="/Dash/Dash" value="Kaydet" class="btn btn-primary mr-3" />

						<a href="@Url.Action("Dash","Dash")" class="btn border button">İptal </a>
					</div>
				}
			</div>

		</div>
	</div>
</body>

ServisFy/Views/Bildirim/Bildirimler.cshtml
@{
	Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<div class="card-body">
	<blockquote class="blockquote blockquote-blue">
		<h2 style="align-content:center"> Tüm Bildirimler</h2> <hr />
		<p>Öğrenciniz servisten indi!</p><hr />
		<p>Servis eve yaklaşmak üzere!</p><hr />
		<p>Öğrenciniz servise bindi.</p><hr />
		<p>Öğrenciniz okula vardı,servisten indi.</p><hr />
		<p>Öğrenciniz servise bindi.</p><hr />
		<p>Servis eve yaklaşmak üzere!</p><hr />
		<p>Öğrenciniz servisten indi!</p><hr />
		<p>Servis eve yaklaşmak üzere!</p><hr />
		<p>Öğrenciniz servise bindi.</p><hr />
		<p>Öğrenciniz okula vardı,servisten indi.</p><hr />
		<p>Öğrenciniz servise bindi.</p><hr />
		<p>Servis eve yaklaşmak üzere!</p><hr />
		<p>Öğrenciniz servisten indi!</p><hr />
		<p>Servis eve yaklaşmak üzere!</p><hr />
		<p>Öğrenciniz servise bindi.</p><hr />
		<p>Öğrenciniz okula vardı,servisten indi.</p><hr />
		<p>Öğrenciniz servise bindi.</p><hr />
		<p>Servis eve yaklaşmak üzere!</p><hr />
		<p>Öğrenciniz servisten indi!</p><hr />
		<p>Servis eve yaklaşmak üzere!</p><hr />
		<p>Öğrenciniz servise bindi.</p><hr />
		<p>Öğrenciniz okula vardı,servisten indi.</p><hr />
		<p>Öğrenciniz servise bindi.</p><hr />
		<p>Servis eve yaklaşmak üzere!</p><hr />
		<p>Öğrenciniz servis binmedi!</p>
	</blockquote>
</div>

ServisFy/Views/Dash/Dash.cshtml
@{
	ViewData["Title"] = "Dash";
	Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}
<!DOCTYPE html>
<html lang="tr">

<head>

</head>
<body>  
<div class="main-panel">
	<div class="content-wrapper">
		<div class="row">
			<div class="col-md-12 grid-margin">
				<div class="row">
					<div class="col-12 col-xl-8 mb-4 mb-xl-0">
						<h3 class="font-weight-bold">Merhaba, Kullanıcı</h3>
						<h6 class="font-weight-normal mb-0">Hoşgeldiniz!</span></h6>
					</div>
					<div class="col-12 col-xl-4">
						<div class="justify-content-end d-flex">
							<div class="dropdown flex-md-grow-1 flex-xl-grow-0">
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-6 grid-margin stretch-card">
				<div class="card tale-bg">
					<div class="card-people mt-auto">
						<img src="~/Dashboard/images/dashboard/card2.png" alt="people">
						<div class="weather-info">
							<div class="d-flex">
								<div>
									<h2 class="mb-0 font-weight-normal"><i class="icon-sun mr-2"></i>33<sup>C</sup></h2>
								</div>
								<div class="ml-2">
									<h4 class="location font-weight-normal">Nilüfer</h4>
									<h6 class="font-weight-normal">Bursa</h6>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-6 grid-margin transparent">
				<div class="row">
					<div class="col-md-6 mb-4 stretch-card transparent">
						<div class="card card-tale">
							<div class="card-body">
								<h3>Toplam Öğrenci</h3>
								<p class="fs-30 mb-2">35909</p>
								<p>40.00% (Son 3 Ay)</p>
							</div>
						</div>
					</div>
					<div class="col-md-6 mb-4 stretch-card transparent">
						<div class="card card-dark-blue">
							<div class="card-body">
								<h3>Toplam Okul</h3>
								<p class="fs-30 mb-2">400</p>
								<p>21.60% (Son 3 Ay)</p>
							</div>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-6 mb-4 mb-lg-0 stretch-card transparent">
						<div class="card card-light-blue">
							<div class="card-body">
								<h3>Toplam Şehir</h3>
								<p class="fs-30 mb-2">48</p>
								<p>5.00% (Son 3 Ay)</p>
							</div>
						</div>
					</div>
					<div class="col-md-6 stretch-card transparent">
						<div class="card card-light-danger">
							<div class="card-body">
								<h3>Memnuniyet</h3>
								<p class="fs-30 mb-2">%99.24</p>
								<p>0.22% (30 days)</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	 </body>
	 <</html>

ServisFy/Views/Register/Register.cshtml
@{
	Layout = null;
}
@model ServisFy.Models.Auth.RegisterDto
<!DOCTYPE html>

<html>
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>Servisfy @@Hesap Oluştur</title>
	<!-- plugins:css -->
	<!-- endinject -->
	<!-- Plugin css for this page -->
	<!-- End plugin css for this page -->
	<!-- inject:css -->
	<link rel="stylesheet" href="../../Dashboard/css/vertical-layout-light/style.css">
	<!-- endinject -->
	<link rel="shortcut icon" href="../../Dashboard/images/favicon.png" />
</head>
<body>
	<div class="container-scroller">
		<div class="container-fluid page-body-wrapper full-page-wrapper">
			<div class="content-wrapper d-flex align-items-center auth px-0">
				<div class="row w-100 mx-0">
					<div class="col-lg-4 mx-auto">
						<div class="auth-form-light text-left py-5 px-4 px-sm-5">
							<div class="brand-logo">
								<img src="~/Dashboard/images/logo.png" alt="logo">
							</div>
							<h4>ServisFY'da yeni misiniz?</h4>
							<h6 class="font-weight-light">Hesap oluşturmak çok kolay!</h6>

							@using (Html.BeginForm())
							{
								<div class="form-group">
									@Html.TextBoxFor(x=>x.k_tc,new {@class="form-control form-control-lg",@placeholder="T.C. Kimlik No", @required="required"})
									
								</div>
								<div class="form-group">
									@Html.TextBoxFor(x=>x.k_adi,new {@class="form-control form-control-lg",@placeholder="Adınız", @required="required"})
									
								</div>
								<div class="form-group">
									@Html.TextBoxFor(x=>x.k_soyadi,new {@class="form-control form-control-lg",@placeholder="Soyadınız", @required="required"})
								</div>
								<div class="form-group">
									@Html.TextBoxFor(x=>x.k_mail,new {@class="form-control form-control-lg",@placeholder="E-Posta",@type="email", @required="required"})
									
								</div>
							
								<div class="form-group">
									@Html.TextBoxFor(x=>x.passwordHash,new {@class="form-control form-control-lg",@placeholder="Şifreniz",@type="password", @required="required"})
									
								</div>
								<div class="form-group">
									@Html.TextBoxFor(x=>x.passwordHash,new {@class="form-control form-control-lg",@placeholder="Şifre Tekrar",@type="password", @required="required"})
									
								</div>
								<div class="mb-4">
									<div class="form-check">
										<label class="form-check-label text-muted">
											<input type="checkbox" class="form-check-input">
											Yukarıda verdiğim bilgiler doğrudur.
										</label>
									</div>
								</div>
								<div class="mt-3">
									<input type="submit" formmethod="post" formaction="/Register/Register" value="Hesap Oluştur" class="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn" />
									
								</div>
								<div class="text-center mt-4 font-weight-light">
									Zaten bir hesabınız var mı? <a href="@Url.Action("Login","Auth")" class="text-primary">Giriş Yapın. </a>
								</div>
							}


						</div>
					</div>
				</div>
			</div>
			<!-- content-wrapper ends -->
		</div>
		<!-- page-body-wrapper ends -->
	</div>
	<!-- container-scroller -->
	<!-- plugins:js -->
	<script src="../../Dashboard/vendors/js/vendor.bundle.base.js"></script>
	<!-- endinject -->
	<!-- Plugin js for this page -->
	<!-- End plugin js for this page -->
	<!-- inject:js -->
	<script src="../../Dashboard/js/off-canvas.js"></script>
	<script src="../../Dashboard/js/hoverable-collapse.js"></script>
	<script src="../../Dashboard/js/template.js"></script>
	<script src="../../Dashboard/js/settings.js"></script>
	<script src="../../Dashboard/js/todolist.js"></script>
	<!-- endinject -->
</body>
</html>

ServisFy/Views/Servis/Servis.cshtml
@{
    ViewData["Title"] = "Servis";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<!DOCTYPE html>
<html lang="tr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Realtime location tracker</title>

    <!-- leaflet css  -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />

    <style>
        body {
            margin: 0;
            padding: 0;
        }

        #map {
            width: 100%;
            height: 100vh;
        }
    </style>
</head>

<body>
    <div id="map"></div>
</body>
</html>

<!-- leaflet js  -->
<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
<script>
    // Map initialization 
    var map = L.map('map').setView([14.0860746, 100.608406], 6);

    //osm layer
    var osm = L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
    });
    osm.addTo(map);

    if(!navigator.geolocation) {
        console.log("Your browser doesn't support geolocation feature!")
    } else {
        setInterval(() => {
            navigator.geolocation.getCurrentPosition(getPosition)
        }, 5000);
    }

    var marker, circle;

    function getPosition(position){
        // console.log(position)
        var lat = position.coords.latitude
        var long = position.coords.longitude
        var accuracy = position.coords.accuracy

        if(marker) {
            map.removeLayer(marker)
        }

        if(circle) {
            map.removeLayer(circle)
        }

        marker = L.marker([lat, long])
        circle = L.circle([lat, long], {radius: accuracy})

        var featureGroup = L.featureGroup([marker, circle]).addTo(map)

        map.fitBounds(featureGroup.getBounds())

        console.log("Your coordinate is: Lat: "+ lat +" Long: "+ long+ " Accuracy: "+ accuracy)
    }

</script>

ServisFy/Views/Shared/_DashboardLayout.cshtml
@{<title>@ViewData["Title"] - Servisfy</title>
	Layout = null;
}
<!DOCTYPE html>
<html lang="tr">

<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>Servisfy!</title>
	<!-- plugins:css -->
	<link rel="stylesheet" href="~/Dashboard/vendors/feather/feather.css">
	<link rel="stylesheet" href="~/Dashboard/vendors/ti-icons/css/themify-icons.css">
	<link rel="stylesheet" href="~/Dashboard/vendors/css/vendor.bundle.base.css">
	<!-- endinject -->
	<!-- Plugin css for this page -->
	<link rel="stylesheet" href="~/Dashboard/vendors/datatables.net-bs4/dataTables.bootstrap4.css">
		<link rel="stylesheet" href="~/ayarlar/style.css">

	<link rel="stylesheet" href="~/Dashboard/vendors/ti-icons/css/themify-icons.css">
	<link rel="stylesheet" type="text/css" href="~/Dashboard/js/select.dataTables.min.css">
	<!-- End plugin css for this page -->
	<!-- inject:css -->
	<link rel="stylesheet" href="~/Dashboard/css/vertical-layout-light/style.css">
	<!-- endinject -->
	<link href="~/img/favicon.png" rel="icon">
	<link href="~/img/apple-touch-icon.png" rel="apple-touch-icon">
</head>

<body>
	<div class="container-scroller">
		<!-- partial:partials/_navbar.html -->
		<nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
			<div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
				<a class="navbar-brand brand-logo mr-5" href="@Url.Action("Dash","Dash")">
					<img src="~/Dashboard/images/logo.png" class="mr-2" alt="logo" />
				</a>

			</div>
			<div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
				<button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
					<span class="icon-menu"></span>
				</button>
				<ul class="navbar-nav mr-lg-2">
					<li class="nav-item nav-search d-none d-lg-block">
						<div class="input-group">
							<div class="input-group-prepend hover-cursor" id="navbar-search-icon">
								<span class="input-group-text" id="search">
									<i class="icon-search"></i>
								</span>
							</div>
							<input type="text" class="form-control" id="navbar-search-input" placeholder="Arama" aria-label="search" aria-describedby="search">
						</div>
					</li>
				</ul>

				<ul class="navbar-nav navbar-nav-right">
					<li class="nav-item dropdown">
						<a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href=# data-toggle="dropdown">
							<i class="icon-bell mx-0"></i>
							<span class="count"></span>
						</a>
						<div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="notificationDropdown">
							<p class="mb-0 font-weight-normal float-left dropdown-header">
								<strong>Bildirimler</strong>
							</p>

							<a href="" class="dropdown-item preview-item">
								<img src="~/png/ogrenci.png" alt="Öğrenci" width="40">
								<div class="preview-item-content">
									<h6 class="preview-subject font-weight-normal">Öğrenciniz servisten indi.</h6>
									<p class="font-weight-light small-text mb-0 text-muted">
										15 dakika önce
									</p>
								</div>
							</a>
							<a href="" class="dropdown-item preview-item">
								<img src="~/png/ogrenci.png" alt="Öğrenci" width="40">

								<div class="preview-item-content">
									<h6 class="preview-subject font-weight-normal">Öğrenciniz servise bindi.</h6>
									<p class="font-weight-light small-text mb-0 text-muted">
										50 dakika önce
									</p>
								</div>

							</a>
							<a href="" class="dropdown-item preview-item">
								<img src="~/png/Servis.png" alt="Servis" width="40">
								<div class="preview-item-content">
									<h6 class="preview-subject font-weight-normal">
										Araç 10 dakika içinde evinize ulaşacaktır.
									</h6>
									<p class="font-weight-light small-text mb-0 text-muted">
										1 saat önce
									</p>
								</div>
							</a>
							<a href="" class="dropdown-item preview-item">
								<img src="~/png/binmedi.png" alt="Binmedi" width="40">
								<div class="preview-item-content">
									<h6 class="preview-subject font-weight-normal">Öğrenciniz servise binmedi.</h6>
									<p class="font-weight-light small-text mb-0 text-muted">
										1 gün önce
									</p>
								</div>
							</a>

							<a href="@Url.Action("Bildirimler","Bildirim")" class="dropdown-item text-center">
								<b>
									<ins>
										Tüm bildirimleri gör
									</ins>
								</b>
							</a>

						</div>
					</li>

					<li class="nav-item nav-profile dropdown">
						<a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
							<img src="~/Dashboard/images/faces/face28.jpg" alt="profile" />
						</a>
						<div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
							<a class="dropdown-item" href="@Url.Action("Ayarlar","Ayarlar")">
								<i class="ti-settings text-primary"></i>
								Ayarlar
							</a>
							<a class="dropdown-item" href="@Url.Action("Login", "Auth")">
								<i class="ti-power-off text-primary"></i>
								Çıkış Yap
							</a>
						</div>
					</li>
				</ul>

			</div>

		</nav>


		<!-- partial -->
		<div class="container-fluid page-body-wrapper">
			<!-- partial:partials/_settings-panel.html -->
			<!-- partial -->
			<!-- partial:partials/_sidebar.html -->
			<nav class="sidebar sidebar-offcanvas" id="sidebar">
				<ul class="nav">
					<li class="nav-item">
						<a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
							<i class="icon-layout menu-icon"></i>
							<span class="menu-title">Öğrenci Takip</span>
							<i class="menu-arrow"></i>
						</a>

						<div class="collapse" id="ui-basic">
							<ul class="nav flex-column sub-menu">
								<li class="nav-item"> <a class="nav-link" href="@Url.Action("OgrNrd","OgrNerede")">Öğrencim Nerede?</a></li>
								<li class="nav-item"> <a class="nav-link" href="@Url.Action("Bildirimler","Bildirim")">Bildirimler</a></li>
							</ul>
						</div>
					</li>
					
					<li class="nav-item">
						<a class="nav-link" data-toggle="collapse" href="#ui-basic2" aria-expanded="false" aria-controls="ui-basic">
							<i class="icon-layout menu-icon"></i>
							<span class="menu-title">Servis Takip</span>
							<i class="menu-arrow"></i>
						</a>
						<div class="collapse" id="ui-basic2">
							<ul class="nav flex-column sub-menu">
								<li class="nav-item"> <a class="nav-link" href="@Url.Action("Servis","Servis")">Servisim Nerede?</a></li>
								<li class="nav-item"> <a class="nav-link" href="@Url.Action("Yonetim","Yonetim")">Servis Yönetim</a></li>
							</ul>
						</div>
					</li>


				</ul>
			</nav>
			@RenderBody()
			<!-- partial -->
			<!-- main-panel ends -->
		</div>
		<!-- page-body-wrapper ends -->
	</div>
	<!-- container-scroller -->
	<!-- plugins:js -->
	<script src="~/Dashboard/vendors/js/vendor.bundle.base.js"></script>
	<!-- endinject -->
	<!-- Plugin js for this page -->
	<script src="~/Dashboard/vendors/chart.js/Chart.min.js"></script>
	<script src="~/Dashboard/vendors/datatables.net/jquery.dataTables.js"></script>
	<script src="~/Dashboard/vendors/datatables.net-bs4/dataTables.bootstrap4.js"></script>
	<script src="~/Dashboard/js/dataTables.select.min.js"></script>

	<!-- End plugin js for this page -->
	<!-- inject:js -->
	<script src="~/Dashboard/js/off-canvas.js"></script>
	<script src="~/Dashboard/js/hoverable-collapse.js"></script>
	<script src="~/Dashboard/js/template.js"></script>
	<script src="~/Dashboard/js/settings.js"></script>
	<script src="~/Dashboard/js/todolist.js"></script>
	<!-- endinject -->
	<!-- Custom js for this page-->
	<script src="~/Dashboard/js/dashboard.js"></script>
	<script src="~/Dashboard/js/Chart.roundedBarCharts.js"></script>
	<!-- End custom js for this page-->
</body>

</html>